### ISSUE TITLE
RocketRML: Mapping a key whose value is a nested structure

### ISSUE THREAD

**Issue by valentinoli** [hestiaAI/hestialabs-experiences#46]
```
authors: Valentin Oliver Loftsson <valentin@hestia.ai>

prefixes:
  ex: http://www.example.com/
  schema: http://schema.org/

sources:
  impressions:
    access: ad-impressions.js
    referenceFormulation: jsonpath
    iterator: $.*.ad.adsUserData.adImpressions.impressions[*]

mappings:
  impression:
    sources:
      - impressions
    po:
      - [ex:targetingCriteria, $(matchedTargetingCriteria)]
```

For this mapping RocketRML returns:
```
<subject> <http://www.example.com/targetingCriteria> "\"[object Object],[object Object]\"" .
```

However, RMLMapper (Java implementation) returns:
```
<subject> <http://www.example.com/targetingCriteria> "{targetingType=Languages, targetingValue=French}".
<subject> <http://www.example.com/targetingCriteria> "{targetingType=Age, targetingValue=35 and up}".
```
